### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by wanguanfu** [linkedin/brooklin#616]
In addition to the java language also provides other language interface, there are detailed interface documentation does not

**Comment by ahmedahamid** [comment]
@wanguanfu Thank you for reaching out.

Could you, please, explain what you would like to accomplish? Are you interested in extending Brooklin using a programming language other than Java or create Brooklin datastreams using a program written in a different programming language?

**Comment by ahmedahamid** [comment]
Closed due to inactivity.
