### ISSUE TITLE
Topic Mirroring did not happen

### ISSUE THREAD

**Issue by configOps** [linkedin/brooklin#617]
I have created 2 kafka cluster 7-a and 7-b with 3 nodes as kafka brokers and 3 zk in each cluster. Started the brooklin server in all 3 nodes of 7-a cluster and created the stream as : 
<img width="1066" alt="Screen Shot 2019-07-22 at 4 51 39 PM" src="https://user-images.githubusercontent.com/18662416/61628803-f06e0e00-aca0-11e9-82ca-8691ac2a8ef5.png">
**But can not see topics in 7-b cluster**. Here is the configuration used :
<img width="970" alt="Screen Shot 2019-07-22 at 4 54 20 PM" src="https://user-images.githubusercontent.com/18662416/61628891-1bf0f880-aca1-11e9-955b-97ae1e39d6e6.png">

Can you provide some pointers to debug/resolve the issue.

**Comment by celiakung** [comment]
@configOps Without looking at the logs, I suspect this might be because your destination Kafka brokers might not be configured with auto.create.topics.enable set to true? Could you send over these Kafka broker configs as well as anything that might've gotten printed in the logs?

**Comment by configOps** [comment]
@celiakung  Yes auto.create.topics.enable was set to false. But after setting it to true and restarting brokers of 7-b cluster. It was still unable to create topics in  7-b cluster. Here is 7-a and 7-b broker config and the brooklin logs attached.
<img width="772" alt="Screen Shot 2019-07-23 at 3 27 33 PM" src="https://user-images.githubusercontent.com/18662416/61703279-e6124980-ad5e-11e9-8991-7b71a5cf5971.png">
<img width="723" alt="Screen Shot 2019-07-23 at 3 28 44 PM" src="https://user-images.githubusercontent.com/18662416/61703281-e6aae000-ad5e-11e9-902f-f8e2cc01190f.png">
[server.log](https://github.com/linkedin/brooklin/files/3421416/server.log)

**Comment by celiakung** [comment]
@configOps Are there any messages in the topics matching the regex `^(first|second)-topic$`?

With `auto.create.topics.enable` set to true, the topics should be automatically created in the destination Kafka cluster once Brooklin attempts to produce messages to the destination. However, these INFO logs suggest that there is nothing in the source topics to mirror:

INFO Processed 0 records in 62 seconds for datastream first-mirroring-stream

**Comment by celiakung** [comment]
@configOps Was there a resolution to this issue? Just wondering so that it might be useful for others in the future.
