### ISSUE TITLE
Documentation/roadmap for CDC

### ISSUE THREAD

**Issue by vicaya** [linkedin/brooklin#620]
What databases are officially supported?

Is MySQL the only database on the roadmap?

**Comment by ahmedahamid** [comment]
@vicaya We use Brooklin with Oracle, Azure EventHubs, and MySQL is in the works. Please, refer to Brooklin's open-sourcing [blog post](https://engineering.linkedin.com/blog/2019/brooklin-open-source) for more details, and always let us know if you have any questions.
