### ISSUE TITLE
 cause=BYOT is not allowed for connector kafkaMirroringConnector. Datastream:

### ISSUE THREAD

**Issue by lifehacking** [linkedin/brooklin#621]
### Subject of the issue
can‘t create ’datastream

### Your environment
* Operating System   Centos7.5
* Brooklin version  1.0.0
* Java version   1.8.0
* Kafka version  1.0.0
* ZooKeeper version   3.4.5

### Steps to reproduce
config  server.properties
`############################# Server Basics #############################
brooklin.server.coordinator.cluster=brooklin-cluster
brooklin.server.coordinator.zkAddress=192.168.1.6:2181
brooklin.server.csvMetricsDir=/tmp/brooklin-example/
brooklin.server.httpPort=32311

########################### Kafka Mirroring connector Configs ######################
brooklin.server.connectorNames=kafkaMirroringConnector
brooklin.server.connector.kafkaMirroringConnector.factoryClassName=com.linkedin.datastream.connectors.kafka.mirrormaker.KafkaMirrorMakerConnectorFactory
brooklin.server.connector.kafkaMirroringConnector.assignmentStrategyFactory=com.linkedin.datastream.server.assignment.BroadcastStrategyFactory

########################### Transport provider configs ######################
brooklin.server.transportProviderNames=kafkaTransportProvider
brooklin.server.transportProvider.kafkaTransportProvider.factoryClassName=com.linkedin.datastream.kafka.KafkaTransportProviderAdminFactory
brooklin.server.transportProvider.kafkaTransportProvider.bootstrap.servers=192.168.5.6:9092
brooklin.server.transportProvider.kafkaTransportProvider.zookeeper.connect=192.168.5.6:2181
brooklin.server.transportProvider.kafkaTransportProvider.client.id=datastream-producer
brooklin.server.transportProvider.kafkaTransportProvider.producersPerTask=1
brooklin.server.transportProvider.kafkaTransportProvider.numProducersPerConnector=5`

curl command
`curl -XPOST http://192.168.6.6:32311/datastream -H "Content-Type: application/json" -d '
{
    "name" : "first-mirroring-stream",
    "connectorName" : "kafkaMirroringConnector",
    "transportProviderName" : "kafkaTransportProvider",
    "source" : {
        "connectionString" : "kafka://192.168.8.6:9092/testtopic"
    },
    "destination" : {
        "connectionString" : "kafka://192.168.5.6:9092/"
    },
    "metadata" : {
        "owner" : "test",
        "system.IsConnectorManagedDestination" : "true",
        "system.reuseExistingDestination" : "false",
        "system.destination.KafkaBrokers" : "192.168.5.6:9092"
    }
}'`

return result

msg=Failed to initialize Datastream: {Status=INITIALIZING, metadata={owner=dalu, system.reuseExistingDestination=false, system.destination.KafkaBrokers=

cause=BYOT is not allowed for connector kafkaMirroringConnector. Datastream: {Status=INITIALIZING, m

**Comment by gauravrkulkarni** [comment]
Are you specifying destination topic name when creating datastream? Mirror maker doesn't allow that, since the use case for mirror maker is to copy data from a topic in source cluster to the same topic in destination cluster.

**Comment by lifehacking** [comment]
> Are you specifying destination topic name when creating datastream? Mirror maker doesn't allow that, since the use case for mirror maker is to copy data from a topic in source cluster to the same topic in destination cluster.

I don‘t  specifying destination topic when creating datastream。
"destination" : { "connectionString" : "kafka://192.168.5.6:9092/" }

**Comment by Jyouping** [comment]
Please do not specify the destination string in for KafkaMirrorMaker when creating the datastream. The dest cluster is configured through transportProvider and Brooklin doesn't allow it to be specified again in the destination section.

**Comment by lifehacking** [comment]
@Jyouping thank you  for the answer.，create datastream ok
