### ISSUE TITLE
Oracle connector

### ISSUE THREAD

**Issue by vaibhav4981** [linkedin/brooklin#623]
Is is possible to connect oracle database to brooklin?

**Comment by ahmedahamid** [comment]
Hi @vaibhav4981 ,

Yes, it is.

At LinkedIn, we use [Oracle GoldenGate](https://www.oracle.com/middleware/technologies/goldengate.html) for replication, and we also use a product called Big Data adapter, which produces these replication events to Kafka. From there, Brooklin reads the Oracle CDC events and repackages them into Brooklin events for our applications to consume.

We are also working on writing another Oracle CDC that reads from Oracle views, which is based on database triggers and not involving Kafka.

**Comment by stackoverflow2** [comment]
Hi @ahmedahamid 
whether you are trying to remove Oracle golden gate from CDC process?

**Comment by ahmedahamid** [comment]
@stackoverflow2 We are using GoldenGate. Are you asking if we'd like to get rid of it?

**Comment by stackoverflow2** [comment]
@ahmedahamid  yes,
I am asking can it be possible to get rid of the golden gate?

**Comment by ahmedahamid** [comment]
We do not have any plans to remove our dependency on GoldenGate. Whether it is technically feasible or not is a question to @celiakung.

**Comment by happyapple668** [comment]
product  "the Big Data adapter" is open source ?

**Comment by ahmedahamid** [comment]
@happyapple668 No, that's an Oracle product. Here's an [introductory article](https://www.ateam-oracle.com/oracle-goldengate-big-data-adapter-apache-kafka-producer).

**Comment by rgibbard** [comment]
> Hi @vaibhav4981 ,
> 
> Yes, it is.
> 
> At LinkedIn, we use [Oracle GoldenGate](https://www.oracle.com/middleware/technologies/goldengate.html) for replication, and we also use a product called Big Data adapter, which produces these replication events to Kafka. From there, Brooklin reads the Oracle CDC events and repackages them into Brooklin events for our applications to consume.
> 
> We are also working on writing another Oracle CDC that reads from Oracle views, which is based on database triggers and not involving Kafka.

Are there any updates on the status of the trigger based connector
