### ISSUE TITLE
After the source partition data is sent to the destination partition, it is distributed randomly. I expect that the source partition data of no. 1 will be sent to no. 1 partition of no. 1 destination

### ISSUE THREAD

**Issue by Bruce2jiang** [linkedin/brooklin#650]
After the source partition data is sent to the destination partition, it is distributed randomly. I expect that the source partition data of no. 1 will be sent to no. 1 partition of no. 1 destination

**Comment by Bruce2jiang** [comment]
According to what rules is the data written to the corresponding destination partition?Which file is the corresponding code?

**Comment by Jyouping** [comment]
In datastream metadata, you can set system.destination.identityPartitioningEnabled = true.
By doing that, you will enable the same partition mapping from source to destination. 

The codes are in the following file: KafkaMirrorMakerDatastreamMetadata.java
and KafkaMirrorMakerConnectorTask.translate()

**Comment by Bruce2jiang** [comment]
Give me a specific example for system.destination.identityPartitioningEnabled  ,thanks

**Comment by Bruce2jiang** [comment]
I set it to go like this : destination.identityPartitioningEnabled  =true ,but have no effect
