### ISSUE TITLE
Kafka feign death

### ISSUE THREAD

**Issue by Bruce2jiang** [linkedin/brooklin#652]
When I used brooklin, there was a problem with the destination kafka, which was manifested as: after writing data from the source kafka, the destination kafka could not synchronize the data
Here's how I did it:
After creating several data streams, the destination kafka will not receive the data. I need to restart the destination kafka. Do you have any general optimization methods

**Comment by Bruce2jiang** [comment]
urgency

**Comment by gauravrkulkarni** [comment]
@Bruce2jiang  is this resolved? If not, can you be more specific? What do you mean by "destination kafka could not synchronize the data". Did the problem go away after restarting destination kafka?

**Comment by gauravrkulkarni** [comment]
Closing the issue because of inactivity
