### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [linkedin/brooklin#817]
(base) [jw@cn05 brooklin]$ ./gradlew clean build
...
Gradle suite > Gradle test > com.linkedin.datastream.kafka.factory.TestSimpleKafkaProducerFactory.testOverrideDefaultProducerConfigs PASSED

> Task :datastream-kafka_2.11:validateSchemaAnnotation NO-SOURCE
> Task :datastream-kafka_2.11:validateTestSchemaAnnotation NO-SOURCE
> Task :datastream-kafka_2.11:check
> Task :datastream-kafka_2.11:build
> Task :datastream-server:assemble
> Task :datastream-server:changedFilesReport NO-SOURCE

> Task :datastream-server:checkstyleMain
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:121: error: Line is longer than 160 characters (found 248). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:124: error: Line is longer than 160 characters (found 164). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:127: error: Line is longer than 160 characters (found 164). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:135: error: Line is longer than 160 characters (found 174). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:141: error: Line is longer than 160 characters (found 200). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/Coordinator.java:142: error: Line is longer than 160 characters (found 216). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:63: error: Line is longer than 160 characters (found 241). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:66: error: Line is longer than 160 characters (found 193). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:67: error: Line is longer than 160 characters (found 176). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:68: error: Line is longer than 160 characters (found 204). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:69: error: Line is longer than 160 characters (found 242). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:70: error: Line is longer than 160 characters (found 195). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:71: error: Line is longer than 160 characters (found 231). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:72: error: Line is longer than 160 characters (found 253). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:73: error: Line is longer than 160 characters (found 192). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:74: error: Line is longer than 160 characters (found 208). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:75: error: Line is longer than 160 characters (found 168). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:76: error: Line is longer than 160 characters (found 177). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:78: error: Line is longer than 160 characters (found 177). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:79: error: Line is longer than 160 characters (found 165). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:81: error: Line is longer than 160 characters (found 165). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:82: error: Line is longer than 160 characters (found 186). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:84: error: Line is longer than 160 characters (found 166). Try to keep lines under 120 characters.
[ant:checkstyle] /data/jw/brooklin/datastream-server/src/main/java/com/linkedin/datastream/server/zk/ZkAdapter.java:85: error: Line is longer than 160 characters (found 241). Try to keep lines under 120 characters.

> Task :datastream-server:checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datastream-server:checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///data/jw/brooklin/datastream-server/build/reports/checkstyle/main.html
  Checkstyle files with violations: 2
  Checkstyle violations by severity: [error:24]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16m 12s
136 actionable tasks: 124 executed, 12 up-to-date
(base) [jw@cn05 brooklin]$

**Comment by vmaheshw** [comment]
Do you have any change in your local version. The main branch compiles fine and the line numbers it is pointing to have less than 160 characters.
